// src/app/methodology/[slug]/page.tsx
'use client';

import { useRouter } from 'next/navigation';
import { methodologies } from '@/lib/methodology-data';
import PracticeView from '@/components/PracticeView';
import { use } from 'react';
import '../methodology.css';

interface PageProps {
  params: Promise<{
    slug: string;
  }>;
}

export default function MethodologyDetailPage({ params }: PageProps) {
  const router = useRouter();
  const resolvedParams = use(params);
  const slug = decodeURIComponent(resolvedParams.slug);

  const handleBack = () => {
    router.back();
  };

  // 检查方法论是否存在
  if (!methodologies[slug]) {
    return (
      <div className="methodology-container">
        <div className="methodology-header">
          <h1>方法论不存在</h1>
          <p>原始 slug: {resolvedParams.slug}</p>
          <p>解码后 slug: {slug}</p>
          <p>可用的方法论: {Object.keys(methodologies).join(', ')}</p>
        </div>
        <div className="methodology-content">
          <button className="btn btn-secondary" onClick={handleBack}>
            ← 返回上一页
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="methodology-container">
      <div className="methodology-wrapper">
        <div className="methodology-header">
          <h1>🎯 {methodologies[slug].name}</h1>
          <p>{methodologies[slug].description}</p>
        </div>

        <div className="methodology-content">
          <PracticeView
            methodologyKey={slug}
            onBack={handleBack}
          />
        </div>
      </div>
    </div>
  );
}

// app/pages/methodology/[slug]/index.vue
<script setup lang="ts">
import { methodologies } from '@/lib/methodology-data'

const route = useRoute()
const slug = computed(() => decodeURIComponent(String(route.params.slug || '')))
const method = computed(() => methodologies[slug.value])
</script>

<template>
  <div class="methodology-container">
    <div v-if="!method" class="methodology-header">
      <h1>方法论不存在</h1>
      <p>slug: {{ slug }}</p>
      <p>可用的方法论: {{ Object.keys(methodologies).join(', ') }}</p>
      <div class="methodology-content">
        <button class="btn btn-secondary" @click="$router.back()">← 返回上一页</button>
      </div>
    </div>

    <div v-else class="methodology-wrapper">
      <div class="methodology-header">
        <h1>🎯 {{ method.name }}</h1>
        <p>{{ method.description }}</p>
      </div>
      <div class="methodology-content">
        <PracticeView :methodology-key="slug" />
      </div>
    </div>
  </div>
</template>
