// app/components/PracticeView.vue
<script setup lang="ts">
import { getMethodologyByKey } from '@/api/methodology'
import { getPracticeRecordsByMethodology } from '@/api/practice'
import { generateAISuggestions } from '@/api/ai'
import { usePracticeHistory } from '@/composables/usePracticeHistory'
import type { Methodology, PracticeRecord, Question, QuestionAnswer } from '@/types/methodology'
import MethodologyHeader from '@/components/MethodologyHeader.vue'

const props = defineProps<{ methodologyKey: string }>()

interface AISuggestion {
  text: string
  selected: boolean
}

const route = useRoute()
const router = useRouter()
const { saveRecord } = usePracticeHistory()

const method = ref<Methodology | null>(null)
const loading = ref(true)
const context = ref('')
const contextTitle = ref('')
const reflection = ref('')
const answers = ref<Record<number, string>>({})
const selectedQuickOptions = ref<Record<number, Set<string>>>({})
const aiSuggestions = ref<Record<number, AISuggestion[]>>({})
const loadingAI = ref<Record<number, boolean>>({})
const autoLoadedAI = ref<Record<number, boolean>>({})
const expandedQuestions = ref<Record<number, boolean>>({})
const historyRecords = ref<PracticeRecord[]>([])
const toast = ref<{ message: string; type: 'success' | 'error' | 'info' } | null>(null)
const showExample = ref(false)

const normalizeQuestion = (q: string | Question): Question => (typeof q === 'string' ? { text: q } : q)
const getQuestionText = (q: string | Question): string => (typeof q === 'string' ? q : q.text)

const showToast = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
  toast.value = { message, type }
  setTimeout(() => {
    toast.value = null
  }, 3000)
}

const loadHistoryRecord = (record: PracticeRecord) => {
  contextTitle.value = record.contextTitle || ''
  context.value = record.context

  const newAnswers: Record<number, string> = {}
  const newSelectedOptions: Record<number, Set<string>> = {}

  record.questionAnswers.forEach((qa) => {
    const questionIndex = qa.questionNumber - 1
    newAnswers[questionIndex] = qa.answer

    const question = method.value?.questions[questionIndex]
    if (question && typeof question !== 'string' && question.quickOptions) {
      const selectedOpts = new Set<string>()
      question.quickOptions.forEach((option) => {
        if (qa.answer.includes(option)) selectedOpts.add(option)
      })
      if (selectedOpts.size > 0) newSelectedOptions[questionIndex] = selectedOpts
    }
  })

  answers.value = newAnswers
  selectedQuickOptions.value = newSelectedOptions
  reflection.value = record.reflection || ''

  const expanded: Record<number, boolean> = {}
  Object.keys(newAnswers).forEach((key) => {
    expanded[Number(key)] = true
  })
  expandedQuestions.value = expanded
}

const loadMethodology = async () => {
  loading.value = true
  try {
    method.value = await getMethodologyByKey(props.methodologyKey)
    historyRecords.value = await getPracticeRecordsByMethodology(props.methodologyKey)

    const timestamp = route.query.timestamp as string | undefined
    if (!timestamp || !method.value) return

    const record = historyRecords.value.find((r) => r.timestamp === timestamp)
    if (record) loadHistoryRecord(record)
  } finally {
    loading.value = false
  }
}

const handleAnswerChange = (index: number, value: string) => {
  answers.value = { ...answers.value, [index]: value }
}

const onAnswerInput = (index: number, event: Event) => {
  handleAnswerChange(index, (event.target as HTMLTextAreaElement).value)
}

const generateAISuggestionsForQuestion = async (questionIndex: number, question: string, isAuto = false) => {
  if (!context.value.trim() && !contextTitle.value.trim()) {
    if (!isAuto) showToast('请先填写问题标题或情景描述，AI才能提供相关建议', 'info')
    return
  }

  loadingAI.value = { ...loadingAI.value, [questionIndex]: true }
  try {
    const fullContext = contextTitle.value.trim() ? `${contextTitle.value}\n\n${context.value}` : context.value
    const aiResponse = await generateAISuggestions({
      context: fullContext,
      question,
      methodologyName: method.value?.name || '',
      previousAnswers: Object.values(answers.value).filter((a) => a.trim()),
    })

    aiSuggestions.value = {
      ...aiSuggestions.value,
      [questionIndex]: aiResponse.map((s) => ({ text: s.text, selected: false })),
    }
    if (isAuto) autoLoadedAI.value = { ...autoLoadedAI.value, [questionIndex]: true }
  } catch {
    if (!isAuto) showToast('AI建议生成失败，请重试', 'error')
  } finally {
    loadingAI.value = { ...loadingAI.value, [questionIndex]: false }
  }
}

const toggleQuestion = (index: number) => {
  const isExpanding = !expandedQuestions.value[index]
  expandedQuestions.value = { ...expandedQuestions.value, [index]: isExpanding }

  if (isExpanding && context.value.trim() && !autoLoadedAI.value[index] && !aiSuggestions.value[index]) {
    const q = method.value?.questions[index]
    if (q) generateAISuggestionsForQuestion(index, getQuestionText(q), true)
  }
}

const selectAISuggestion = (questionIndex: number, suggestionIndex: number) => {
  const suggestions = aiSuggestions.value[questionIndex]
  if (!suggestions) return

  const suggestion = suggestions[suggestionIndex]
  const currentAnswer = answers.value[questionIndex] || ''

  if (suggestion.selected) {
    const parts = currentAnswer.split('\n\n').filter((part) => part.trim() !== suggestion.text.trim())
    handleAnswerChange(questionIndex, parts.join('\n\n'))
  } else {
    handleAnswerChange(questionIndex, currentAnswer ? `${currentAnswer}\n\n${suggestion.text}` : suggestion.text)
  }

  aiSuggestions.value = {
    ...aiSuggestions.value,
    [questionIndex]: suggestions.map((s, i) => (i === suggestionIndex ? { ...s, selected: !s.selected } : s)),
  }
}

const selectQuickOption = (questionIndex: number, option: string) => {
  const currentAnswer = answers.value[questionIndex] || ''
  const selected = selectedQuickOptions.value[questionIndex] || new Set<string>()

  if (selected.has(option)) {
    const nextSelected = new Set(selected)
    nextSelected.delete(option)
    selectedQuickOptions.value = { ...selectedQuickOptions.value, [questionIndex]: nextSelected }
    const parts = currentAnswer.split('; ').filter((part) => part.trim() !== option.trim())
    handleAnswerChange(questionIndex, parts.join('; '))
    return
  }

  const nextSelected = new Set(selected)
  nextSelected.add(option)
  selectedQuickOptions.value = { ...selectedQuickOptions.value, [questionIndex]: nextSelected }
  handleAnswerChange(questionIndex, currentAnswer ? `${currentAnswer}; ${option}` : option)
}

const handleSubmit = async () => {
  if (!method.value) return

  if (!context.value.trim() && !contextTitle.value.trim()) {
    showToast('请填写问题标题或情景描述！', 'error')
    return
  }

  const questionAnswers: QuestionAnswer[] = method.value.questions.map((q, i) => ({
    questionNumber: i + 1,
    question: getQuestionText(q),
    answer: answers.value[i] || '',
  }))

  if (!questionAnswers.some((qa) => qa.answer.trim())) {
    showToast('请至少回答一个问题！', 'error')
    return
  }

  await saveRecord({
    timestamp: new Date().toISOString(),
    methodology: props.methodologyKey,
    methodologyName: method.value.name,
    methodologyCategory: method.value.category,
    methodologyDescription: method.value.description,
    methodologyTags: method.value.tags,
    contextTitle: contextTitle.value,
    context: context.value,
    questionAnswers,
    reflection: reflection.value,
  })

  showToast(`✅ 已保存 ${Object.values(answers.value).filter((a) => a.trim()).length} 个回答`, 'success')
  historyRecords.value = await getPracticeRecordsByMethodology(props.methodologyKey)
  contextTitle.value = ''
  context.value = ''
  reflection.value = ''
  answers.value = {}
  selectedQuickOptions.value = {}
}

const currentPayload = computed(() => {
  if (!method.value) return null
  return {
    methodology: props.methodologyKey,
    methodologyName: method.value.name,
    methodologyCategory: method.value.category,
    methodologyDescription: method.value.description,
    methodologyTags: method.value.tags,
    exportDate: new Date().toISOString(),
    contextTitle: contextTitle.value,
    context: context.value,
    questionAnswers: method.value.questions.map((q, i) => ({ questionNumber: i + 1, question: getQuestionText(q), answer: answers.value[i] || '' })),
    reflection: reflection.value,
  }
})

const handleExport = () => {
  if (!currentPayload.value || (!context.value.trim() && !contextTitle.value.trim() && Object.values(answers.value).every((a) => !a?.trim()))) {
    showToast('当前页面没有填写任何内容！', 'error')
    return
  }

  const blob = new Blob([JSON.stringify(currentPayload.value, null, 2)], { type: 'application/json' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${method.value?.name || props.methodologyKey}-${new Date().toISOString().split('T')[0]}.json`
  link.click()
  URL.revokeObjectURL(url)
  showToast('📥 已导出当前内容', 'success')
}

const handleCopyJSON = async () => {
  if (!currentPayload.value || (!context.value.trim() && !contextTitle.value.trim() && Object.values(answers.value).every((a) => !a?.trim()))) {
    showToast('当前页面没有填写任何内容！', 'error')
    return
  }

  await navigator.clipboard.writeText(JSON.stringify(currentPayload.value, null, 2))
  showToast('📋 已复制当前内容的 JSON 数据', 'success')
}

const handleVisualize = () => {
  if (!method.value) return
  router.push(`/visualization?methodology=${encodeURIComponent(props.methodologyKey)}&name=${encodeURIComponent(method.value.name)}`)
}

onMounted(loadMethodology)
watch(() => route.query.timestamp, loadMethodology)
</script>

<template>
  <div v-if="loading" class="loading-text">加载中...</div>
  <div v-else-if="!method">方法论不存在</div>
  <div v-else class="practice-view-compact">
    <MethodologyHeader
      :methodology="method"
      :methodology-key="props.methodologyKey"
      :has-answers="Object.keys(answers).length > 0"
      :history-count="historyRecords.length"
      @back="router.back()"
      @export="handleExport"
      @copy-json="handleCopyJSON"
      @save="handleSubmit"
      @visualize="handleVisualize"
    />

    <div v-if="toast" :class="`toast-notification toast-${toast.type}`">{{ toast.message }}</div>

    <div class="practice-content-grid">
      <div class="practice-main-column">
        <div class="example-section">
          <div class="example-header clickable" @click="showExample = !showExample">
            <span>💡 查看示例</span>
            <span class="expand-icon">{{ showExample ? '−' : '+' }}</span>
          </div>
          <div v-if="showExample" class="example-content"><p>{{ method.example }}</p></div>
        </div>

        <div class="context-box">
          <label class="compact-label">📋 问题标题</label>
          <input v-model="contextTitle" type="text" class="compact-input" placeholder="用一句话概括你的问题..." />

          <label class="compact-label" style="margin-top: 12px">📝 问题情景/上下文</label>
          <textarea v-model="context" class="compact-textarea" placeholder="详细描述问题的背景、情景和相关信息..." rows="4" />
        </div>

        <div class="questions-compact">
          <div class="questions-header">
            <h3>🤔 思考框架</h3>
            <span class="questions-count">{{ method.questions.length }} 个问题</span>
          </div>

          <div class="questions-accordion">
            <div v-for="(q, i) in method.questions" :key="i" :class="['question-card', expandedQuestions[i] ? 'expanded' : '']">
              <div class="question-header" @click="toggleQuestion(i)">
                <div class="question-title">
                  <span class="question-num">Q{{ i + 1 }}</span>
                  <span class="question-text">{{ normalizeQuestion(q).text }}</span>
                </div>
                <div class="question-status">
                  <span v-if="answers[i]?.trim()" class="answered-badge">✓</span>
                  <span class="expand-icon">{{ expandedQuestions[i] ? '−' : '+' }}</span>
                </div>
              </div>

              <div v-if="expandedQuestions[i]" class="question-body">
                <div v-if="(normalizeQuestion(q).quickOptions || []).length > 0" class="quick-options">
                  <div class="quick-options-label">💡 快速选择：</div>
                  <div class="quick-options-grid">
                    <button
                      v-for="option in (normalizeQuestion(q).quickOptions || [])"
                      :key="option"
                      :class="['quick-option-btn', selectedQuickOptions[i]?.has(option) ? 'selected' : '']"
                      @click.stop="selectQuickOption(i, option)"
                    >
                      {{ option }}
                    </button>
                  </div>
                </div>

                <textarea
                  class="compact-answer"
                  :value="answers[i] || ''"
                  :placeholder="normalizeQuestion(q).placeholder || '写下你的思考，或点击上方快速选择...'"
                  rows="3"
                  @click.stop
                  @input="onAnswerInput(i, $event)"
                />

                <div class="ai-section">
                  <div v-if="loadingAI[i]" class="ai-loading">🤖 AI正在分析你的问题描述...</div>

                  <div v-if="aiSuggestions[i] && aiSuggestions[i].length > 0" class="ai-suggestions-container">
                    <div class="ai-suggestions-label">✨ AI建议：</div>
                    <div class="ai-suggestions">
                      <div
                        v-for="(suggestion, si) in aiSuggestions[i]"
                        :key="si"
                        :class="['suggestion-chip', suggestion.selected ? 'selected' : '']"
                        @click.stop="selectAISuggestion(i, si)"
                      >
                        <span v-if="suggestion.selected" class="check-icon">✓</span>
                        {{ suggestion.text }}
                      </div>
                    </div>
                  </div>

                  <button
                    v-if="!loadingAI[i] && !aiSuggestions[i] && context.trim()"
                    class="btn-ai-manual"
                    @click.stop="generateAISuggestionsForQuestion(i, getQuestionText(q))"
                  >
                    🔄 重新生成AI建议
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="reflection-box">
          <label class="compact-label">💭 反思和收获</label>
          <textarea v-model="reflection" class="compact-textarea" placeholder="通过这次思考，你有什么收获和感悟..." rows="4" />
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/PracticeView.tsx
'use client';

import { useState, useEffect } from 'react';
import { useSearchParams, useRouter } from 'next/navigation';
import { getMethodologyByKey } from '@/api/methodology';
import { usePracticeHistory } from '@/hooks/usePracticeHistory';
import { getPracticeRecordsByMethodology } from '@/api/practice';
import { QuestionAnswer, Methodology, Question, PracticeRecord } from '@/types/methodology';
import { generateAISuggestions } from '@/api/ai';
import MethodologyHeader from './MethodologyHeader';
import '../app/methodology/practice-compact.css';

interface PracticeViewProps {
  methodologyKey: string;
  onBack: () => void;
}

interface AISuggestion {
  text: string;
  selected: boolean;
}

// 辅助函数：将问题转换为统一格式
const normalizeQuestion = (q: string | Question): Question => {
  if (typeof q === 'string') {
    return { text: q };
  }
  return q;
};

// 辅助函数：获取问题文本
const getQuestionText = (q: string | Question): string => {
  return typeof q === 'string' ? q : q.text;
};

export default function PracticeView({ methodologyKey, onBack }: PracticeViewProps) {
  const searchParams = useSearchParams();
  const router = useRouter();
  const [method, setMethod] = useState<Methodology | null>(null);
  const [loading, setLoading] = useState(true);
  const { saveRecord } = usePracticeHistory();

  const [context, setContext] = useState('');
  const [contextTitle, setContextTitle] = useState('');
  const [answers, setAnswers] = useState<Record<number, string>>({});
  const [selectedQuickOptions, setSelectedQuickOptions] = useState<Record<number, Set<string>>>({});
  const [aiSuggestions, setAiSuggestions] = useState<Record<number, AISuggestion[]>>({});
  const [loadingAI, setLoadingAI] = useState<Record<number, boolean>>({});
  const [autoLoadedAI, setAutoLoadedAI] = useState<Record<number, boolean>>({});
  const [reflection, setReflection] = useState('');
  const [expandedQuestions, setExpandedQuestions] = useState<Record<number, boolean>>({});
  const [historyRecords, setHistoryRecords] = useState<PracticeRecord[]>([]);
  const [showHistoryPrompt, setShowHistoryPrompt] = useState(false);
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' | 'info' } | null>(null);
  const [showExample, setShowExample] = useState(false);

  // 处理可视化按钮点击 - 跳转到新页面
  const handleVisualize = () => {
    if (!method) return;
    
    // 构建 URL 参数
    const params = new URLSearchParams({
      methodology: methodologyKey,
      name: method.name,
    });
    
    // 跳转到可视化页面
    router.push(`/visualization?${params.toString()}`);
  };

  useEffect(() => {
    const loadMethodology = async () => {
      try {
        setLoading(true);
        const data = await getMethodologyByKey(methodologyKey);
        setMethod(data);
        
        // 加载历史记录
        const records = await getPracticeRecordsByMethodology(methodologyKey);
        setHistoryRecords(records);
        
        // 检查 URL 参数中是否有 timestamp
        const timestamp = searchParams.get('timestamp');
        
        if (timestamp) {
          // 如果有 timestamp，查找对应的记录并回填
          const targetRecord = records.find(r => r.timestamp === timestamp);
          if (targetRecord && data) {
            // 直接在这里回填数据，避免依赖问题
            setContextTitle(targetRecord.contextTitle || '');
            setContext(targetRecord.context);
            
            const newAnswers: Record<number, string> = {};
            const newSelectedOptions: Record<number, Set<string>> = {};
            
            targetRecord.questionAnswers.forEach((qa) => {
              const questionIndex = qa.questionNumber - 1;
              newAnswers[questionIndex] = qa.answer;
              
              const question = data.questions[questionIndex];
              if (question && typeof question !== 'string' && question.quickOptions) {
                const selectedOpts = new Set<string>();
                question.quickOptions.forEach(option => {
                  if (qa.answer.includes(option)) {
                    selectedOpts.add(option);
                  }
                });
                if (selectedOpts.size > 0) {
                  newSelectedOptions[questionIndex] = selectedOpts;
                }
              }
            });
            
            setAnswers(newAnswers);
            setSelectedQuickOptions(newSelectedOptions);
            
            if (targetRecord.reflection) {
              setReflection(targetRecord.reflection);
            }
            
            // 展开所有有答案的问题
            const newExpanded: Record<number, boolean> = {};
            Object.keys(newAnswers).forEach(key => {
              newExpanded[parseInt(key)] = true;
            });
            setExpandedQuestions(newExpanded);
            
            // 不显示历史记录提示
            setShowHistoryPrompt(false);
          }
        }
      } catch (error) {
        console.error('Failed to load methodology:', error);
      } finally {
        setLoading(false);
      }
    };
    
    loadMethodology();
  }, [methodologyKey, searchParams]);

  if (loading) {
    return <div className="loading-text">加载中...</div>;
  }

  if (!method) {
    return <div>方法论不存在</div>;
  }

  const loadHistoryRecord = (record: PracticeRecord) => {
    // 回填问题描述
    setContextTitle(record.contextTitle || '');
    setContext(record.context);
    
    // 回填答案
    const newAnswers: Record<number, string> = {};
    const newSelectedOptions: Record<number, Set<string>> = {};
    
    record.questionAnswers.forEach((qa) => {
      const questionIndex = qa.questionNumber - 1;
      newAnswers[questionIndex] = qa.answer;
      
      // 尝试恢复快速选项的选中状态
      const question = method.questions[questionIndex];
      if (question && typeof question !== 'string' && question.quickOptions) {
        const selectedOpts = new Set<string>();
        question.quickOptions.forEach(option => {
          if (qa.answer.includes(option)) {
            selectedOpts.add(option);
          }
        });
        if (selectedOpts.size > 0) {
          newSelectedOptions[questionIndex] = selectedOpts;
        }
      }
    });
    
    setAnswers(newAnswers);
    setSelectedQuickOptions(newSelectedOptions);
    
    // 回填反思
    if (record.reflection) {
      setReflection(record.reflection);
    }
    
    // 关闭提示
    setShowHistoryPrompt(false);
    
    // 展开所有有答案的问题
    const newExpanded: Record<number, boolean> = {};
    Object.keys(newAnswers).forEach(key => {
      newExpanded[parseInt(key)] = true;
    });
    setExpandedQuestions(newExpanded);
  };

  const handleAnswerChange = (index: number, value: string) => {
    setAnswers(prev => ({ ...prev, [index]: value }));
  };

  const toggleQuestion = (index: number) => {
    const isExpanding = !expandedQuestions[index];
    setExpandedQuestions(prev => ({ ...prev, [index]: isExpanding }));
    
    // 当展开问题且有问题描述时，自动加载AI建议
    if (isExpanding && context.trim() && !autoLoadedAI[index] && !aiSuggestions[index]) {
      const question = method?.questions[index];
      if (question) {
        const questionText = getQuestionText(question);
        generateAISuggestionsForQuestion(index, questionText, true);
      }
    }
  };

  const generateAISuggestionsForQuestion = async (questionIndex: number, question: string, isAuto = false) => {
    if (!context.trim() && !contextTitle.trim()) {
      if (!isAuto) {
        showToast('请先填写问题标题或情景描述，AI才能提供相关建议', 'info');
      }
      return;
    }

    setLoadingAI(prev => ({ ...prev, [questionIndex]: true }));
    
    try {
      const fullContext = contextTitle.trim() 
        ? `${contextTitle}\n\n${context}` 
        : context;
      
      const aiResponse = await generateAISuggestions({
        context: fullContext,
        question,
        methodologyName: method?.name || '',
        previousAnswers: Object.values(answers).filter(a => a.trim())
      });
      
      const suggestions: AISuggestion[] = aiResponse.map(s => ({
        text: s.text,
        selected: false
      }));
      
      setAiSuggestions(prev => ({ ...prev, [questionIndex]: suggestions }));
      if (isAuto) {
        setAutoLoadedAI(prev => ({ ...prev, [questionIndex]: true }));
      }
    } catch (error) {
      console.error('Failed to generate AI suggestions:', error);
      if (!isAuto) {
        showToast('AI建议生成失败，请重试', 'error');
      }
    } finally {
      setLoadingAI(prev => ({ ...prev, [questionIndex]: false }));
    }
  };

  const selectAISuggestion = (questionIndex: number, suggestionIndex: number) => {
    const suggestions = aiSuggestions[questionIndex];
    if (!suggestions) return;

    const suggestion = suggestions[suggestionIndex];
    const selectedText = suggestion.text;
    const currentAnswer = answers[questionIndex] || '';
    
    // 检查是否已选中
    const isSelected = suggestion.selected;
    
    if (isSelected) {
      // 取消选中：从答案中移除该建议
      // 使用双换行符分割，移除该建议，然后重新组合
      const parts = currentAnswer.split('\n\n').filter(part => part.trim() !== selectedText.trim());
      const newAnswer = parts.join('\n\n');
      
      handleAnswerChange(questionIndex, newAnswer);
      
      // 标记为未选中
      setAiSuggestions(prev => ({
        ...prev,
        [questionIndex]: suggestions.map((s, i) => 
          i === suggestionIndex ? { ...s, selected: false } : s
        )
      }));
    } else {
      // 选中：将建议添加到答案中
      const newAnswer = currentAnswer 
        ? `${currentAnswer}\n\n${selectedText}` 
        : selectedText;
      
      handleAnswerChange(questionIndex, newAnswer);
      
      // 标记为已选中
      setAiSuggestions(prev => ({
        ...prev,
        [questionIndex]: suggestions.map((s, i) => 
          i === suggestionIndex ? { ...s, selected: true } : s
        )
      }));
    }
  };

  const selectQuickOption = (questionIndex: number, option: string) => {
    const currentAnswer = answers[questionIndex] || '';
    const selectedOptions = selectedQuickOptions[questionIndex] || new Set<string>();
    
    // 检查是否已选中
    const isSelected = selectedOptions.has(option);
    
    if (isSelected) {
      // 取消选中：从答案中移除该选项
      const newSelectedOptions = new Set(selectedOptions);
      newSelectedOptions.delete(option);
      
      // 将答案按分号分割，移除该选项，然后重新组合
      const parts = currentAnswer.split('; ').filter(part => part.trim() !== option.trim());
      const newAnswer = parts.join('; ');
      
      handleAnswerChange(questionIndex, newAnswer);
      setSelectedQuickOptions(prev => ({
        ...prev,
        [questionIndex]: newSelectedOptions
      }));
    } else {
      // 选中：添加到答案中
      const newAnswer = currentAnswer 
        ? `${currentAnswer}; ${option}` 
        : option;
      
      const newSelectedOptions = new Set(selectedOptions);
      newSelectedOptions.add(option);
      
      handleAnswerChange(questionIndex, newAnswer);
      setSelectedQuickOptions(prev => ({
        ...prev,
        [questionIndex]: newSelectedOptions
      }));
    }
  };

  const showToast = (message: string, type: 'success' | 'error' | 'info' = 'info') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 3000);
  };

  const handleSubmit = async () => {
    if (!context.trim() && !contextTitle.trim()) {
      showToast('请填写问题标题或情景描述！', 'error');
      return;
    }

    const questionAnswers: QuestionAnswer[] = method.questions.map((q, i) => ({
      questionNumber: i + 1,
      question: getQuestionText(q),
      answer: answers[i] || ''
    }));

    const hasAnswer = questionAnswers.some(qa => qa.answer.trim());
    if (!hasAnswer) {
      showToast('请至少回答一个问题！', 'error');
      return;
    }

    const record = {
      timestamp: new Date().toISOString(),
      methodology: methodologyKey,
      methodologyName: method.name,
      methodologyCategory: method.category,
      methodologyDescription: method.description,
      methodologyTags: method.tags,
      contextTitle,
      context,
      questionAnswers,
      reflection
    };

    try {
      await saveRecord(record);
      showToast(`✅ 已保存 ${Object.values(answers).filter(a => a.trim()).length} 个回答`, 'success');
      
      // 重新加载历史记录
      const records = await getPracticeRecordsByMethodology(methodologyKey);
      setHistoryRecords(records);
      
      // 清空表单
      setContextTitle('');
      setContext('');
      setAnswers({});
      setSelectedQuickOptions({});
      setReflection('');
    } catch (error) {
      console.error('Failed to save record:', error);
      showToast('保存失败，请重试', 'error');
    }
  };

  const handleExport = () => {
    // 检查是否有当前填写的内容
    if (!context.trim() && !contextTitle.trim() && Object.values(answers).every(a => !a?.trim())) {
      showToast('当前页面没有填写任何内容！', 'error');
      return;
    }

    // 准备当前页面的数据
    const questionAnswers: QuestionAnswer[] = method.questions.map((q, i) => ({
      questionNumber: i + 1,
      question: getQuestionText(q),
      answer: answers[i] || ''
    }));

    const currentData = {
      methodology: methodologyKey,
      methodologyName: method?.name,
      methodologyCategory: method?.category,
      methodologyDescription: method?.description,
      methodologyTags: method?.tags,
      exportDate: new Date().toISOString(),
      contextTitle,
      context,
      questionAnswers,
      reflection
    };

    // 创建JSON字符串
    const dataStr = JSON.stringify(currentData, null, 2);
    const dataBlob = new Blob([dataStr], { type: 'application/json' });
    
    // 创建下载链接
    const url = URL.createObjectURL(dataBlob);
    const link = document.createElement('a');
    link.href = url;
    
    // 生成文件名：方法论名称-日期.json
    const fileName = `${method?.name || methodologyKey}-${new Date().toISOString().split('T')[0]}.json`;
    link.download = fileName;
    
    // 触发下载
    link.click();
    
    // 清理URL对象
    URL.revokeObjectURL(url);
    
    // 显示成功提示
    showToast(`📥 已导出当前内容`, 'success');
  };

  const handleCopyJSON = async () => {
    // 检查是否有当前填写的内容
    if (!context.trim() && !contextTitle.trim() && Object.values(answers).every(a => !a?.trim())) {
      showToast('当前页面没有填写任何内容！', 'error');
      return;
    }

    // 准备当前页面的数据
    const questionAnswers: QuestionAnswer[] = method.questions.map((q, i) => ({
      questionNumber: i + 1,
      question: getQuestionText(q),
      answer: answers[i] || ''
    }));

    const currentData = {
      methodology: methodologyKey,
      methodologyName: method?.name,
      methodologyCategory: method?.category,
      methodologyDescription: method?.description,
      methodologyTags: method?.tags,
      exportDate: new Date().toISOString(),
      contextTitle,
      context,
      questionAnswers,
      reflection
    };

    // 创建JSON字符串
    const dataStr = JSON.stringify(currentData, null, 2);

    try {
      await navigator.clipboard.writeText(dataStr);
      showToast(`📋 已复制当前内容的 JSON 数据`, 'success');
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
      showToast('复制失败，请重试', 'error');
    }
  };

  return (
    <div className="practice-view-compact">
      <MethodologyHeader
        methodology={method}
        methodologyKey={methodologyKey}
        onBack={onBack}
        onExport={handleExport}
        onCopyJSON={handleCopyJSON}
        onSave={handleSubmit}
        onVisualize={handleVisualize}
        hasAnswers={Object.keys(answers).length > 0}
        historyCount={historyRecords.length}
      />

      {toast && (
        <div className={`toast-notification toast-${toast.type}`}>
          {toast.message}
        </div>
      )}

      {/* 历史记录提示 */}
      {showHistoryPrompt && historyRecords.length > 0 && (
        <div className="history-prompt">
          <div className="history-prompt-header">
            <span className="history-icon">📋</span>
            <span className="history-title">发现 {historyRecords.length} 条历史记录</span>
            <button 
              className="btn-close-prompt"
              onClick={() => setShowHistoryPrompt(false)}
            >
              ✕
            </button>
          </div>
          <div className="history-list">
            {historyRecords.slice(0, 3).map((record, index) => (
              <div key={index} className="history-item">
                <div className="history-item-info">
                  <div className="history-context">
                    {record.contextTitle && (
                      <strong>{record.contextTitle}</strong>
                    )}
                    {record.contextTitle && record.context && ' - '}
                    {record.context.substring(0, 60)}
                    {record.context.length > 60 ? '...' : ''}
                  </div>
                  <div className="history-meta">
                    {new Date(record.timestamp).toLocaleString('zh-CN')} · 
                    {record.questionAnswers.filter(qa => qa.answer).length} 个回答
                  </div>
                </div>
                <button
                  className="btn-load-history"
                  onClick={() => loadHistoryRecord(record)}
                >
                  查看回填
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      <div className="practice-content-grid">
        {/* 单列布局：输入框 + 思考框架 */}
        <div className="practice-main-column">
          {/* 示例（可折叠） */}
          <div className="example-section">
            <div 
              className="example-header clickable" 
              onClick={() => setShowExample(!showExample)}
            >
              <span>💡 查看示例</span>
              <span className="expand-icon">{showExample ? '−' : '+'}</span>
            </div>
            {showExample && (
              <div className="example-content">
                <p>{method.example}</p>
              </div>
            )}
          </div>

          {/* 问题描述 */}
          <div className="context-box">
            <label className="compact-label">📋 问题标题</label>
            <input
              type="text"
              className="compact-input"
              value={contextTitle}
              onChange={(e) => setContextTitle(e.target.value)}
              placeholder="用一句话概括你的问题..."
            />
            
            <label className="compact-label" style={{ marginTop: '12px' }}>📝 问题情景/上下文</label>
            <textarea
              className="compact-textarea"
              value={context}
              onChange={(e) => setContext(e.target.value)}
              placeholder="详细描述问题的背景、情景和相关信息..."
              rows={4}
            />
          </div>

          {/* 思考框架 */}
          <div className="questions-compact">
            <div className="questions-header">
              <h3>🤔 思考框架</h3>
              <span className="questions-count">{method.questions.length} 个问题</span>
            </div>

          <div className="questions-accordion">
            {method.questions.map((q, i) => {
              const question = normalizeQuestion(q);
              const questionText = question.text;
              const quickOptions = question.quickOptions || [];
              const placeholder = question.placeholder || '写下你的思考，或点击上方快速选择...';
              
              return (
                <div key={i} className={`question-card ${expandedQuestions[i] ? 'expanded' : ''}`}>
                  <div className="question-header" onClick={() => toggleQuestion(i)}>
                    <div className="question-title">
                      <span className="question-num">Q{i + 1}</span>
                      <span className="question-text">{questionText}</span>
                    </div>
                    <div className="question-status">
                      {answers[i]?.trim() && <span className="answered-badge">✓</span>}
                      <span className="expand-icon">{expandedQuestions[i] ? '−' : '+'}</span>
                    </div>
                  </div>

                  {expandedQuestions[i] && (
                    <div className="question-body">
                      {/* 快速选择选项 - 仅当有选项时显示 */}
                      {quickOptions.length > 0 && (
                        <div className="quick-options">
                          <div className="quick-options-label">💡 快速选择：</div>
                          <div className="quick-options-grid">
                            {quickOptions.map((option, oi) => {
                              const isSelected = selectedQuickOptions[i]?.has(option) || false;
                              return (
                                <button
                                  key={oi}
                                  className={`quick-option-btn ${isSelected ? 'selected' : ''}`}
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    selectQuickOption(i, option);
                                  }}
                                >
                                  {option}
                                </button>
                              );
                            })}
                          </div>
                        </div>
                      )}

                      <textarea
                        className="compact-answer"
                        value={answers[i] || ''}
                        onChange={(e) => handleAnswerChange(i, e.target.value)}
                        placeholder={placeholder}
                        rows={3}
                        onClick={(e) => e.stopPropagation()}
                      />

                      {/* AI建议区域 - 自动显示 */}
                      <div className="ai-section">
                        {loadingAI[i] && (
                          <div className="ai-loading">
                            🤖 AI正在分析你的问题描述...
                          </div>
                        )}

                        {aiSuggestions[i] && aiSuggestions[i].length > 0 && (
                          <div className="ai-suggestions-container">
                            <div className="ai-suggestions-label">✨ AI建议：</div>
                            <div className="ai-suggestions">
                              {aiSuggestions[i].map((suggestion, si) => (
                                <div 
                                  key={si} 
                                  className={`suggestion-chip ${suggestion.selected ? 'selected' : ''}`}
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    selectAISuggestion(i, si);
                                  }}
                                >
                                  {suggestion.selected && <span className="check-icon">✓</span>}
                                  {suggestion.text}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                        {!loadingAI[i] && !aiSuggestions[i] && context.trim() && (
                          <button 
                            className="btn-ai-manual"
                            onClick={(e) => {
                              e.stopPropagation();
                              generateAISuggestionsForQuestion(i, questionText);
                            }}
                          >
                            🔄 重新生成AI建议
                          </button>
                        )}
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
          </div>

          {/* 反思和收获 */}
          <div className="reflection-box">
            <label className="compact-label">💭 反思和收获</label>
            <textarea
              className="compact-textarea"
              value={reflection}
              onChange={(e) => setReflection(e.target.value)}
              placeholder="通过这次思考，你有什么收获和感悟..."
              rows={4}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
